# Generated by Django 3.1.2 on 2020-12-28 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('website', models.URLField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('synopsis', models.TextField()),
                ('image', models.URLField(max_length=120)),
                ('status', models.CharField(choices=[('Released', 'Released'), ('Prototype', 'Prototype'), ('Devlog', 'Devlog'), ('On hold', 'Onhold'), ('In development', 'Indev'), ('Canceled', 'Canceled')], max_length=14)),
                ('releaseDate', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('currencyType', models.CharField(choices=[('USD', 'Usd'), ('EURO', 'Euro')], max_length=4)),
                ('buyURL', models.URLField(max_length=120)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamesearcher.author')),
                ('genres', models.ManyToManyField(to='gamesearcher.Genre')),
                ('platforms', models.ManyToManyField(to='gamesearcher.Platform')),
            ],
        ),
    ]
