# Generated by Django 3.1.2 on 2020-12-28 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamesearcher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='website',
        ),
    ]
