# Generated by Django 3.1.2 on 2021-01-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamesearcher', '0002_remove_author_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='synopsis',
            new_name='description',
        ),
    ]
