# Generated by Django 3.1.2 on 2021-01-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesearcher', '0003_auto_20210102_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='author',
        ),
        migrations.AddField(
            model_name='game',
            name='authors',
            field=models.ManyToManyField(to='gamesearcher.Author'),
        ),
    ]
