# Generated by Django 3.1.2 on 2021-01-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesearcher', '0004_auto_20210102_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.TextField(default='No tags', max_length=300),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('Released', 'Released'), ('Prototype', 'Prototype'), ('On hold', 'Onhold'), ('In development', 'Indev'), ('Canceled', 'Canceled')], max_length=14),
        ),
    ]
