# Generated by Django 3.1.2 on 2021-01-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamesearcher', '0005_auto_20210102_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='releaseDate',
            new_name='publishDate',
        ),
    ]
