# Generated by Django 3.1.2 on 2021-01-02 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamesearcher', '0006_auto_20210102_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='currencyType',
        ),
    ]
