# Generated by Django 3.1.2 on 2021-01-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesearcher', '0009_auto_20210102_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndieGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(default='No description')),
                ('imageURL', models.URLField(max_length=120)),
                ('tags', models.TextField(default='No tags', max_length=300)),
                ('status', models.CharField(choices=[('Released', 'Released'), ('Prototype', 'Prototype'), ('On hold', 'Onhold'), ('In development', 'Indev'), ('Canceled', 'Canceled')], max_length=14)),
                ('publishDate', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('downloadURL', models.URLField(max_length=120)),
                ('authors', models.ManyToManyField(to='gamesearcher.Author')),
                ('genres', models.ManyToManyField(to='gamesearcher.Genre')),
                ('platforms', models.ManyToManyField(to='gamesearcher.Platform')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainstreamGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(default='No description')),
                ('imageURL', models.URLField(max_length=120)),
                ('tags', models.TextField(default='No tags', max_length=300)),
                ('authors', models.ManyToManyField(to='gamesearcher.Author')),
                ('genres', models.ManyToManyField(to='gamesearcher.Genre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
