# Generated by Django 3.1.2 on 2021-01-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamesearcher', '0010_auto_20210104_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
    ]
