# Generated by Django 3.1.2 on 2021-01-04 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamesearcher', '0011_auto_20210104_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainstreamgame',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='mainstreamgame',
            name='description',
        ),
    ]
