# Generated by Django 3.1.2 on 2021-01-04 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamesearcher', '0012_auto_20210104_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indiegame',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='mainstreamgame',
            options={'ordering': ['title']},
        ),
    ]
