# Generated by Django 3.1.2 on 2021-01-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesearcher', '0014_igsuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='igsuser',
            name='recommendedGames',
            field=models.ManyToManyField(related_name='RecommendedGames', to='gamesearcher.IndieGame'),
        ),
    ]
