# Generated by Django 3.1.2 on 2021-01-04 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamesearcher', '0015_igsuser_recommendedgames'),
    ]

    operations = [
        migrations.RenameField(
            model_name='igsuser',
            old_name='indiegamesLiked',
            new_name='likedIndieGames',
        ),
        migrations.RenameField(
            model_name='igsuser',
            old_name='mainstreamgamesLiked',
            new_name='likedMainstreamGames',
        ),
    ]
