# Generated by Django 3.1.2 on 2021-01-05 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamesearcher', '0017_auto_20210105_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platform',
            options={'ordering': ['name']},
        ),
    ]
