# Generated by Django 3.1.2 on 2021-01-06 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesearcher', '0018_auto_20210105_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igsuser',
            name='likedIndieGames',
            field=models.ManyToManyField(blank=True, to='gamesearcher.IndieGame'),
        ),
        migrations.AlterField(
            model_name='igsuser',
            name='likedMainstreamGames',
            field=models.ManyToManyField(blank=True, to='gamesearcher.MainstreamGame'),
        ),
        migrations.AlterField(
            model_name='igsuser',
            name='platforms',
            field=models.ManyToManyField(blank=True, to='gamesearcher.Platform'),
        ),
        migrations.AlterField(
            model_name='indiegame',
            name='genres',
            field=models.ManyToManyField(blank=True, to='gamesearcher.Genre'),
        ),
        migrations.AlterField(
            model_name='indiegame',
            name='platforms',
            field=models.ManyToManyField(blank=True, to='gamesearcher.Platform'),
        ),
        migrations.AlterField(
            model_name='mainstreamgame',
            name='genres',
            field=models.ManyToManyField(blank=True, to='gamesearcher.Genre'),
        ),
        migrations.AlterField(
            model_name='mainstreamgame',
            name='platforms',
            field=models.ManyToManyField(blank=True, to='gamesearcher.Platform'),
        ),
    ]
