# Generated by Django 3.1.2 on 2021-01-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesearcher', '0019_auto_20210106_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='indiegame',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='mainstreamgame',
            name='tags',
        ),
        migrations.AddField(
            model_name='indiegame',
            name='tags',
            field=models.ManyToManyField(blank=True, to='gamesearcher.Tag'),
        ),
        migrations.AddField(
            model_name='mainstreamgame',
            name='tags',
            field=models.ManyToManyField(blank=True, to='gamesearcher.Tag'),
        ),
    ]
