# Generated by Django 3.1.2 on 2021-01-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamesearcher', '0021_auto_20210122_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indiegame',
            name='price',
        ),
    ]
