# Generated by Django 3.1.2 on 2021-01-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesearcher', '0022_remove_indiegame_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='igsuser',
            name='genres',
            field=models.ManyToManyField(blank=True, to='gamesearcher.Genre'),
        ),
    ]
