# Generated by Django 3.1.2 on 2021-01-28 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamesearcher', '0023_igsuser_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='igsuser',
            name='genres',
        ),
    ]
