# Generated by Django 3.1.2 on 2021-01-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamesearcher', '0024_remove_igsuser_genres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['id']},
        ),
    ]
