# Generated by Django 3.1.2 on 2021-01-28 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamesearcher', '0025_auto_20210128_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
    ]
