# Generated by Django 3.1.2 on 2021-01-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesearcher', '0026_auto_20210128_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='igsuser',
            name='recommendedGames',
            field=models.ManyToManyField(blank=True, related_name='recommendedGames', to='gamesearcher.IndieGame'),
        ),
    ]
